---

  - name: Add Prometheus Chart Repository
    kubernetes.core.helm_repository:
      name: prometheus-charts
      repo_url: "https://prometheus-community.github.io/helm-charts"

  - name: Install prometheus helm chart
    kubernetes.core.helm:
      name: kube-state-metrics
      chart_ref: prometheus-charts/kube-state-metrics
      chart_version: 4.7.0
      release_namespace: kube-state-metrics
      update_repo_cache: true
      create_namespace: true
      values_files:
        - roles/prometheus-k8s-metrics/files/kube-state-metrics.yaml
      values:
        replicas: 3