---
# tasks file for traefik

  - name: Add Traefik Chart Repository
    kubernetes.core.helm_repository:
      name: traefik
      repo_url: "https://helm.traefik.io/traefik"

  - name: Deploy Traefik
    kubernetes.core.helm:
      name: traefik
      chart_ref: traefik/traefik
      chart_version: 10.7.1
      release_namespace: traefik
      create_namespace: true
      update_repo_cache: true
      values:
        deployment:
          replicas: 3
        providers:
          kubernetesCRD:
            enabled: true
            allowCrossNamespace: true
            namespaces: traefik
          kubernetesIngress:
            enabled: true
            namespaces: traefik
        service:
          enabled: true
          type: LoadBalancer
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-name: "{{ aws_load_balancer_name }}"
            service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "{{ load_balancer_tags }}"
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "{{ load_balancer_backend_protocol }}"
            service.beta.kubernetes.io/aws-load-balancer-internal: "{{ load_balancer_internal }}"
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "{{ load_balancer_ssl_cert }}"
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "{{ load_balancer_ssl_ports }}"
            service.beta.kubernetes.io/aws-load-balancer-type: "{{ load_balancer_type }}"
        persistence:
          size: 256Mi

  - name: Create middleware_redirect
    kubernetes.core.k8s:
      state: present
      src: roles/traefik/files/middleware_redirect.yaml